name: fastcorr_backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  dotenv: ^4.2.0
  firebase_admin: ^0.3.0+2
  firedart: ^0.9.8
  googleapis: any
  googleapis_auth: ^1.6.0
  http: ^1.3.0
  path: ^1.9.1
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5
  uuid: ^4.5.1
  

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
